name: Auto build all files with python script

on:
  push:
    branches: 
      - main

permissions: write-all

jobs:
  auto-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Python script
        run: |
          python auto.py
      
      - name: Update README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs(action): Update README.md"
          git push https://open17@github.com/open17/slides.git HEAD:main
      
      - name: Move files
        run: |
          mv ./dist/* ./

      - name: Push Page branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "feat(action): Generate page"
          git pull
          git push --force https://open17@github.com/open17/slides.git HEAD:pages
      